#!/bin/bash
export TERM=xterm-256color
export VERSION="1.0.0"
export VERB=0

# Color stuff
RED="\e[38;5;196m"
ORANGE="\e[38;5;166m"
GRAY="\e[38;5;245m"
GREEN="\e[38;5;42m"

# Print version
echo -e "\n🔥 Ember Datacenter "$ORANGE"v$VERSION\e[0m\n";

# Check if root
if [[ $EUID > 0 ]]; then
	echo -e "   "$RED"Error:\e[0m This script must be run as root."
	exit 1
fi

# Check if command is passed
function errorcheck() {
	if [[ $? > 0 ]]; then
		echo -ne $RED"FAILED\e[0m\n\n"
		echo -e "   "$GRAY"Try again with "$ORANGE"--verbose"$GRAY" for more information.\e[0m\n"
		exit 1
	fi
}

# Define help page
function help() {
	echo -e "   This script is used to configure a "$ORANGE"Ember VPN\e[0m instance.\n"
	echo -e "   "$RED"USAGE:\e[0m $0 [--options] command [--flag=value]\n"
	echo -e "   "$ORANGE"OPTIONS:\e[0m"
	echo -e "      -h, --help      Show this help page"
	echo -e "      -v, --verbose   Enable verbose mode"
	echo -e
	echo -e "   "$ORANGE"COMMANDS:\e[0m"
	echo -e "      enroll          Enroll this server as a VPN node"
	echo -e
}

# Install dependencies
function install() {
	echo -ne "   "$GRAY"Installing dependencies... \e[0m"
	if [[ $VERB = 1 ]]; then
		echo -e
		apt-get update || errorcheck
		apt-get upgrade -y || errorcheck
		apt-get install easy-rsa openvpn curl jq ruby -y || errorcheck
	else
		apt-get update &> /dev/null || errorcheck
		apt-get upgrade -y &> /dev/null || errorcheck
		apt-get install easy-rsa openvpn curl jq ruby -y &> /dev/null || errorcheck
	fi
	echo -ne $GREEN"DONE\e[0m\n"
}

# Configure easy-rsa
function init_pki() {
	echo -ne "   "$GRAY"Initializing Easy RSA PKI... \e[0m"

	mkdir -p ~/easy-rsa ~/client-configs
	ln -fs /usr/share/easy-rsa/* ~/easy-rsa/
	cd ~/easy-rsa
	chmod 700 ~/easy-rsa
	echo 'set_var EASYRSA_ALGO "ec"' > vars
	echo 'set_var EASYRSA_DIGEST "sha512"' >> vars
	./easyrsa --batch init-pki &> /dev/null || errorcheck

	echo -ne $GREEN"DONE\e[0m\n"

}

# Download certificates
function download_certs() {
	echo -ne "   "$GRAY"Downloading Ember VPN CA... \e[0m"

	if [[ $VERB = 1 ]]; then
		echo -e
		curl --request GET \
			--url https://api.embervpn.org/rsa/download-ca \
			> /usr/local/share/ca-certificates/ca.crt
		cp /usr/local/share/ca-certificates/ca.crt ~/client-configs/keys
		cp /usr/local/share/ca-certificates/ca.crt /etc/openvpn/server
		update-ca-certificates
	else
		curl -s --request GET \
			--url https://api.embervpn.org/rsa/download-ca \
			> /usr/local/share/ca-certificates/ca.crt
		cp /usr/local/share/ca-certificates/ca.crt ~/client-configs/keys &> /dev/null
		cp /usr/local/share/ca-certificates/ca.crt /etc/openvpn/server &> /dev/null
		update-ca-certificates &> /dev/null
	fi

	echo -ne $GREEN"DONE\e[0m\n"
}

function download_csr() {

	echo -ne "   "$GRAY"Requesting server certificate... \e[0m"
	if [[ $VERB = 1 ]]; then

		echo -e
		./easyrsa --batch --req-cn="$NAME" gen-req $NAME nopass || errorcheck
		cp pki/private/$NAME.key /etc/openvpn/server/server.key || errorcheck
		curl --request POST \
			--url https://api.embervpn.org/rsa/sign-request \
			--header 'Content-Type: application/json' \
			--data '{"req": "'$(base64 -w0 pki/reqs/$NAME.req)'"}' \
			> /etc/openvpn/server/server.crt || errorcheck

	else
		
		./easyrsa --batch --req-cn="$NAME" gen-req $NAME nopass &> /dev/null || errorcheck
		cp pki/private/$NAME.key /etc/openvpn/server/server.key &> /dev/null || errorcheck
		curl --request POST \
			--url https://api.embervpn.org/rsa/sign-request \
			--header 'Content-Type: application/json' \
			--data '{"req": "'$(base64 -w0 pki/reqs/$NAME.req)'"}' \
			> /etc/openvpn/server/server.crt &> /dev/null || errorcheck

	fi

	echo -ne $GREEN"DONE\e[0m\n"
}

function download_conf() {
	echo -ne "   "$GRAY"Downloading server config... \e[0m"
	if [[ $VERB = 1 ]]; then
		echo -e
		POST=$(curl --request POST \
			--url https://api.embervpn.org/rsa/download-server-config \
			--header 'Content-Type: application/json' \
			--data '{
				"ip": "'$IP'",
				"iface": "'$IFACE'",
				"network": "'$NETWORK'",
				"subnet": "'$SUBNET'",
				"port": "'$PORT'",
				"proto": "'$PROTO'",
				"hostname": "'$NAME'"
			}' || errorcheck)
	else
		POST=$(curl -s --request POST \
			--url https://api.embervpn.org/rsa/download-server-config \
			--header 'Content-Type: application/json' \
			--data '{
				"ip": "'$IP'",
				"iface": "'$IFACE'",
				"network": "'$NETWORK'",
				"subnet": "'$SUBNET'",
				"port": "'$PORT'",
				"proto": "'$PROTO'",
				"hostname": "'$NAME'"
			}' || errorcheck)
	fi

	# Add the CA's public key to the authorized keys
	sed -i '/ember_ca/d' ~/.ssh/authorized_keys || errorcheck
	echo $CA_PUB >> ~/.ssh/authorized_keys || errorcheck
	echo "$CONFIG" > /etc/openvpn/server/server.conf || errorcheck

	echo -ne $GREEN"DONE\e[0m\n"

	HASH=$(echo $POST | jq -r '.hash')

}

function conf_ufw() {
	echo -ne "   "$GRAY"Configuring Firewall... \e[0m"

	CIDR=$NETWORK$(awk -F. '{
		split($0, octets)
		for (i in octets) {
			mask += 8 - log(2**8 - octets[i])/log(2);
		}
		print "/" mask
	}' <<< $SUBNET)

	# Configure Firewall rules
	RULES=$(cat <<-END
		# START OPENVPN RULES
		*nat
		:POSTROUTING ACCEPT [0:0]
		-A POSTROUTING -s $CIDR -o $IFACE -j MASQUERADE
		COMMIT
		# END OPENVPN RULES
	END

	);

	if [[ $VERB = 1 ]]; then
		echo -e
		sed -i '/# START OPENVPN RULES/,/# END OPENVPN RULES/d' /etc/ufw/before.rules
		echo "$RULES" | cat - /etc/ufw/before.rules > temp && mv temp /etc/ufw/before.rules
		sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw
		ufw allow $PORT/$PROTO
		ufw allow OpenSSH
		ufw disable && ufw --force enable
	else
		sed -i '/# START OPENVPN RULES/,/# END OPENVPN RULES/d' /etc/ufw/before.rules &> /dev/null
		echo "$RULES" | cat - /etc/ufw/before.rules > temp && mv temp /etc/ufw/before.rules &> /dev/null
		sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/g' /etc/default/ufw &> /dev/null
		ufw allow $PORT/$PROTO &> /dev/null
		ufw allow OpenSSH &> /dev/null
		ufw disable &> /dev/null && ufw --force enable &> /dev/null
	fi

	echo -ne $GREEN"DONE\e[0m\n"
}

# Get command flags and args
while [ "$1" ]; do

	# if $1 starts with - or --, it's a flag
	if [[ $1 == -* ]]; then
		case $1 in
			-h|--help)
				help
				exit 0
				;;
			-v|--verbose)
				VERB=1
				echo -e "   "$GRAY"Verbose mode enabled\e[0m"
				;;
			*)
				echo -e "   "$RED"Error:\e[0m Unknown flag "$ORANGE"$1\e[0m. Try "$ORANGE"$0 --help\e[0m"
				exit 1
				;;
		esac
		shift
		continue
	fi

	# if $1 is a command, run it
	case $1 in
		install)
			shift
			install $@
			;;
		init-pki)
			shift
			init_pki $@
			;;
		enroll)
			shift
			install
			init_pki
			download_certs

			ARGUMENT_LIST=(
				"name"
				"iface"
				"ip"
				"port"
				"proto"
				"network"
				"subnet"
			)
			OPTS=$(getopt \
				--longoptions "$(printf "%s:," "${ARGUMENT_LIST[@]}")" \
				--name "$(basename "$0")" \
				--options "" \
				-- "$@"
			)
			eval set -- $OPTS

			# Initialize enroll variables
			NAME=$(hostname)
			IFACE=$(ip r | head -n 1 | awk '{print $5}')
			IP=$(curl http://checkip.dyndns.org/ 2> /dev/null | ruby -pe '$_=$_.scan(/\d+\.\d+\.\d+\.\d+/)' | jq -r '.[0]')
			PORT="1194"
			PROTO="tcp"
			NETWORK="10.8.0.0"
			SUBNET="255.255.255.0"

			while [[ $# > 0 ]]; do
				case ${1} in
					--name)
						shift
						NAME=$1
						;;
					--iface)
						shift
						IFACE=$1
						;;
					--ip)
						shift
						IP=$1
						;;
					--port)
						shift
						PORT=$1
						;;
					--proto)
						shift
						PROTO=$1
						;;
					--network)
						shift
						NETWORK=$1
						;;
					--subnet)
						SUBNET=$2 && shift 2
						;;
					--)
						shift
						break
					;;
				esac
				shift
			done

			download_csr $NAME
			download_conf $NAME $IFACE $IP $PORT $PROTO $NETWORK $SUBNET

			# Parse the response
			CA_PUB=$(echo $POST | jq -r '.ed25519')
			CONFIG=$(echo $POST | jq -r '.config' | base64 -w0 --decode)

			conf_ufw $NETWORK $SUBNET $PROTO $PORT

			# Start openvpn
			if [[ $VERB = 1 ]]; then
				systemctl -f enable openvpn-server@server.service &> /dev/null || errorcheck
				systemctl start openvpn-server@server.service &> /dev/null || errorcheck
			else
				systemctl -f enable openvpn-server@server.service &> /dev/null || errorcheck
				systemctl start openvpn-server@server.service &> /dev/null || errorcheck
			fi

			echo -e "\n   Server is convigured as:"$ORANGE" $HASH\e[0m"

			;;
		*)
			echo -e "   "$RED"Error:\e[0m Unknown command "$ORANGE"$1\e[0m. Try "$ORANGE"$0 --help\e[0m"
			exit 1
			;;
	esac

	echo -e

done